### ISSUE TITLE
Incompatibility with sodium ThinGL

### ISSUE THREAD

**Issue by ElliotS2007** [FlashyReese/sodium-extra-fabric#26] opened 2021-05-08 17:50 UTC
Sodium Extra seems to be incompatible with sodium ThinGL update

**Comment by FlashyReese** [comment] 2021-05-08 18:00
Can you provide a crash report or a log?

**Comment by ElliotS2007** [comment] 2021-05-08 18:58
https://gist.githubusercontent.com/natanfudge/e40acdc20b509e60d8ef93d7ea616d70/raw/2acc819f963ac44faff2dbee72d826bbe585d5e4/crash.txt

**Comment by DragonEggBedrockBreaking** [comment] 2021-06-05 07:56
Thingl has been merged into sodium next now, so this could still be an issue?

**Comment by DragonEggBedrockBreaking** [comment] 2021-06-05 08:19
Confirmed crash on new 1.16.x/next after thingl was merged: https://gist.github.com/DragonEggBedrockBreaking/27f000bcf0e6570608fb262c963e3224

**Comment by FlashyReese** [comment] 2021-06-05 08:31
I won't be updating this anytime soon until Sodium for 1.17 is released. There are plenty of changes coming, I don't want to waste my time fixing this then removing it because of 1.17

**Comment by DragonEggBedrockBreaking** [comment] 2021-06-05 08:34
> I won't be updating this anytime soon until Sodium for 1.17 is released. There are plenty of changes coming, I don't want to waste my time fixing this then removing it because of 1.17

I mostly mentioned this because the mod's version b eing bumped to 0.2.0 and a possible future release could mean tha many players update to the now stable builds from curseforge/modrinth/github releases, and then complain that sodium extra no longer works. Maybe you could at least do a breaks sodium 0.2.0 clause in fabric.mod.json and then tell people to use an older version of sodium extra?

**Comment by PhantomG27249** [comment] 2021-06-08 01:13
1.17 is based on thingl so it might be worth doing the fix now

**Closed as completed** 2021-06-17 22:03 UTC
Labels: bug, pending release
