### ISSUE TITLE
plz make this mod a 1.17 version plz

### ISSUE THREAD

**Issue by HsLaranjinho** [FlashyReese/sodium-extra-fabric#51] opened 2021-07-15 20:16 UTC

**Comment by K0-RR** [comment] 2021-07-15 21:52
Duplicate of https://github.com/FlashyReese/sodium-extra-fabric/issues/43.

There is no official release of Sodium for 1.17 **yet** so how do you want a Sodium addon to be on 1.17?

**Comment by DragonEggBedrockBreaking** [comment] 2021-07-15 21:56
And if you have the knowledge to compile sodium 1.17, which you will not be helped with, you already also have the knowledge to compile the 1.17 branch of this mod.

**Comment by Sanluli36li** [comment] 2021-07-16 09:41
In fact, you can get it in actions, but stability cannot be guaranteed

**Closed as completed** 2021-07-17 22:06 UTC
Labels: invalid
