### ISSUE TITLE
Crash on start (something about reeses_sodium_options/client/gui/SodiumVideoOptionsScreen classnotfound)

### ISSUE THREAD

**Issue by AmibeSkyfy16** [FlashyReese/sodium-extra-fabric#102] opened 2021-11-17 12:31 UTC
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/FlashyReese/sodium-extra-fabric/issues?q=) and did not find an issue describing my bug.

### Minecraft version.

1.17.1

### Sodium Extra version.

0.3.6

### Sodium version.

0.3.2+build.7 (Iris shaders)

### What happened?

my modpack crash since i updated to 0.3.6. But now if i inverse the update (back to 0.3.5, i have some crash too)

### Relevant log.

logs: https://pastebin.com/8xFM1Pj7
crash-report-client: https://pastebin.com/GWZXhhV7
crash-report-server: https://pastebin.com/nnH5SDwy

**Comment by FlashyReese** [comment] 2021-11-17 13:33
The message you read is a warning not the cause of the crash. The log says Adorn is to blame but I'm not sure what's going on.

~~I also see you have Iris and Sodium Standalone installed together.~~ Are you using the CurseForge Launcher?

**Comment by AmibeSkyfy16** [comment] 2021-11-17 13:54
Yes im using curseforge launcher, i think adorn is not the first cause, maybe iris. But its strange, because i played a lot this days and no bug, and without any change (maybe just sodium extra update), the game crashed today.

**Comment by FlashyReese** [comment] 2021-11-17 14:00
I'm not sure if the CurseForge Launcher is bundling Sodium itself because I have it marked as a dependency on CF.

**Comment by AmibeSkyfy16** [comment] 2021-11-17 15:36
Yes maybe i have to delete sodium and ust using iris-and-sodium-mc1.17-1.1.2+build.9.jar

**Comment by AmibeSkyfy16** [comment] 2021-11-17 15:44
Yes i deleted sodium and its works now. the tricks is installing sodium extra and removing sodium create new crash (failed to launch) https://postimg.cc/0MTRjbHS

**Closed as completed** 2021-11-17 15:58 UTC
Labels: bug
